### ISSUE TITLE
[Feature] 도파밍 메인페이지

### ISSUE THREAD

**Issue by rabbitate** [Do-Farming/do-farming_Front#2]
## 📌 Issue

<img width="240" alt="스크린샷 2024-06-21 오후 3 01 10" src="https://github.com/Do-Farming/do-farming_Front/assets/56537513/d3bb4e41-5fff-40c0-8a41-01b4c899b1b3">

## 📜 To-do

- [x] 카드 정보 받아오기
- [x] 메인페이지 ui / ux 작업
- [ ] 기기별 css 수정
- [x] 3초마다 리렌더링 해결
