### ISSUE TITLE
[Feature] 이상형 월드컵 선택 페이지

### ISSUE THREAD

**Issue by rabbitate** [Do-Farming/do-farming_Front#26]
## 📌 Issue
<img width="240" alt="스크린샷 2024-06-25 오후 2 06 36" src="https://github.com/Do-Farming/do-farming_Front/assets/56537513/0a8a9fb4-b548-40c7-a9cb-1361167412c2">
<img width="240" alt="스크린샷 2024-06-26 오전 9 34 08" src="https://github.com/Do-Farming/do-farming_Front/assets/56537513/f2e3bac5-e3e2-4e03-baf4-da5a12ad1972">
<img width="240" alt="스크린샷 2024-06-26 오전 9 35 43" src="https://github.com/Do-Farming/do-farming_Front/assets/56537513/d36a603c-d226-4c10-9a61-77cddb87b150">
<img width="240" alt="스크린샷 2024-06-30 오후 2 57 00" src="https://github.com/Do-Farming/do-farming_Front/assets/56537513/531f95cc-a6d2-4e63-9966-8f0b7dac04fd">
<img width="240" alt="스크린샷 2024-06-30 오후 2 58 03" src="https://github.com/Do-Farming/do-farming_Front/assets/56537513/fd0ddc95-cb6f-451f-a792-ee66de303d6b">

## 📜 To-do

- [x] 이상형 월드컵 종류 선택 페이지 ui / ux 작업
- [x] 카드 이상형 월드컵 진행 중 화면
- [x] 카드 이상형 월드컵 진행 중 화면 css(가로 길이가 긴 카드 90도 회전)
- [x] 카드 이상형 월드컵 진행 중 화면 css(카드 이름이 긴 경우, 혜택이 컨테이너 벗어날 경우)
- [x] 카드 이상형 월드컵 진행 progress Bar
- [x] 카드 이상형 월드컵 우승 화면
- [x] 나만의 카드 만들기 화면 - 생성하기
- [x] 나만의 카드 만들기 화면 - 생성 완료
