### ISSUE TITLE
[Feature] 사물인식 API 불러오기 

### ISSUE THREAD

**Issue by chaeyeon-yang** [Do-Farming/do-farming_Front#64]
## 📜 To-do

- [x] 칫솔, 책, 시계, 숟가락, 헤어드라이기만의 후보 군
- [ ] [ toothbrush, book, clock, spoon , hair drier ]
- [x] 사용자가 찍은 사진 중 위와 같은 분류의 응답 받아오기

## ETC

https://aiopen.etri.re.kr/guide/od
