### ISSUE TITLE
[Refactor] 메인페이지 성능 최적화

### ISSUE THREAD

**Issue by rabbitate** [Do-Farming/do-farming_Front#67]
## 📜 To-do

currentIndex가 바뀌면서 컴포넌트가 리렌더링 됨(아래 문제들이 발생)
- [x] cardList 불필요한 리렌더링 방지
- [x] Pagination 불필요한 리렌더링 방지
- [x] handleMomentumScrollEnd 함수 최적화
